#include "eeprom_addresses.h"

const uint16_t VirtAddVarTab[NB_OF_VAR] = {
    ADR_SYSTEM_MARKER, ADR_SW_VERSION, ADR_FLASH_VERSION, ADR_CURRENT_CONFIG,
    ADR_FFB_CF_FILTER, ADR_FFB_FR_FILTER, ADR_FFB_DA_FILTER, ADR_FFB_IN_FILTER,
    ADR_FFB_EFFECTS1, ADR_FFB_EFFECTS2, ADR_FFB_EFFECTS3,
    ADR_AXIS1_CONFIG, ADR_AXIS1_MAX_SPEED, ADR_AXIS1_MAX_ACCEL,
    ADR_AXIS1_ENDSTOP, ADR_AXIS1_POWER, ADR_AXIS1_DEGREES,
    ADR_AXIS1_EFFECTS1, ADR_AXIS1_EFFECTS2, ADR_AXIS1_ENC_RATIO,
    ADR_AXIS1_SPEEDACCEL_FILTER, ADR_AXIS1_POSTPROCESS1,
    ADR_ODRIVE_CANID, ADR_ODRIVE_SETTING1_M0, ADR_ODRIVE_SETTING1_M1,
    ADR_ODRIVE_OFS_M0, ADR_ODRIVE_OFS_M1,
    // GPIO inputs (Phase 4.x)
    ADR_GPIO1_CFG, ADR_GPIO1_AMIN, ADR_GPIO1_AMAX,
    ADR_GPIO2_CFG, ADR_GPIO2_AMIN, ADR_GPIO2_AMAX,
    ADR_GPIO3_CFG, ADR_GPIO3_AMIN, ADR_GPIO3_AMAX,
    ADR_GPIO4_CFG, ADR_GPIO4_AMIN, ADR_GPIO4_AMAX,
    // slots livres
    0x04F0, 0x04F1, 0x04F2,
};
